###register user
POST http://localhost:4000/user-api/users
Content-Type: application/json 

{
    "firstName":"author1",
     "lastName":"",
     "email"    :"auth1@gmail.com",
     " password":"auth1",
      " role"   :"AUTHOR",
     "profileImgUrl" : "",
                              
}

###user login
POST http://localhost:4000/auth/users
Content-Type: application/json 

{

}